DROP TRIGGER IF EXISTS video_bookmark_cull ON video_bookmarks;
DROP FUNCTION IF EXISTS cull_old_bookmarks;
DROP TABLE IF EXISTS video_bookmarks;
DROP TABLE IF EXISTS video_metadata;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS audio_metadata;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS photo_metadata;
DROP TABLE IF EXISTS media_items;
DROP TABLE IF EXISTS collection_access;
DROP TABLE IF EXISTS collections;
DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS server_config;
